# Generated by Django 5.2 on 2025-05-01 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Oylik Maosh (UZS)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='salary_status',
            field=models.CharField(blank=True, choices=[('Paid', 'Berilgan'), ('Pending', 'Kutilmoqda')], max_length=10, null=True, verbose_name='Oylik Holati'),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Do'kon nomi")),
                ('subscription_plan', models.CharField(default='Free', max_length=50, verbose_name='Obuna Tarifi')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Amal qilish muddati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_stores', to=settings.AUTH_USER_MODEL, verbose_name="Do'kon Egasi")),
            ],
            options={
                'verbose_name': "Do'kon",
                'verbose_name_plural': "Do'konlar",
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='users.store', verbose_name="Do'kon"),
        ),
    ]
