# Generated by Django 5.2 on 2025-05-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='salary_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name="Oylik To'lanadigan Sana"),
        ),
    ]
