# Generated by Django 5.2 on 2025-05-03 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('users', '0002_userprofile_address_userprofile_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='subscriptions.subscriptionplan', verbose_name='Obuna Tarifi'),
        ),
    ]
