# Generated by Django 5.2 on 2025-05-09 05:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_amount', models.DecimalField(decimal_places=2, help_text='Nasiya olingandagi asl narx (foizsiz)', max_digits=17, verbose_name='Mahsulot Narxi (UZS)')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, help_text="Nasiya uchun qo'shiladigan umumiy foiz (butun muddat uchun)", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Foiz Stavka (%)')),
                ('term_months', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Muddat (oylar)')),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name="Boshlang'ich To'lov (UZS)")),
                ('total_amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=17, verbose_name="Jami To'lanishi Kerak (Foiz Bilan, UZS)")),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name="Taxminiy Oylik To'lov (UZS)")),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text="Boshlang'ich to'lovni ham o'z ichiga oladi", max_digits=17, verbose_name="Jami To'langan (UZS)")),
                ('status', models.CharField(choices=[('Active', 'Faol'), ('Paid', 'Yakunlangan'), ('Overdue', 'Kechikkan'), ('Cancelled', 'Bekor qilingan')], default='Active', max_length=10, verbose_name='Holati')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana')),
                ('return_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Qaytarish Tuzatishi (UZS)')),
            ],
            options={
                'verbose_name': 'Nasiya Rejasi',
                'verbose_name_plural': 'Nasiya Rejalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name="To'lov Sanasi")),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=17, verbose_name="To'lanishi Kerak Summa")),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name="Haqiqatda To'langan")),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langan")),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name="Haqiqiy To'lov Sanasi")),
            ],
            options={
                'verbose_name': "To'lov Grafigi Yozuvi",
                'verbose_name_plural': "To'lov Grafigi Yozuvlari",
                'ordering': ['plan', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=17, verbose_name="To'lov summasi (UZS)")),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="To'lov sanasi")),
                ('payment_method', models.CharField(choices=[('Naqd', 'Naqd'), ('Karta', 'Karta'), ("O'tkazma", "O'tkazma")], default='Naqd', max_length=10, verbose_name="To'lov usuli")),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Qabul qilgan xodim')),
            ],
            options={
                'verbose_name': "Nasiya To'lovi",
                'verbose_name_plural': "Nasiya To'lovlari",
                'ordering': ['-payment_date'],
            },
        ),
    ]
