# Generated by Django 5.2 on 2025-04-30 12:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0002_salereturn_salereturnitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Umumiy qarz (UZS)')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name="Jami to'langan (UZS)")),
                ('next_payment_date', models.DateField(blank=True, null=True, verbose_name="Keyingi to'lov sanasi")),
                ('status', models.CharField(choices=[('Active', 'Faol'), ('Paid', 'Yakunlangan'), ('Overdue', 'Kechikkan'), ('Cancelled', 'Bekor qilingan')], default='Active', max_length=10, verbose_name='Holati')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana')),
                ('return_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Qaytarish tuzatishi (UZS)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_plans', to='sales.customer', verbose_name='Mijoz')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installmentplan', to='sales.sale', verbose_name='Asosiy Sotuv')),
            ],
            options={
                'verbose_name': 'Nasiya Rejasi',
                'verbose_name_plural': 'Nasiya Rejalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=17, verbose_name="To'lov summasi (UZS)")),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="To'lov sanasi")),
                ('payment_method', models.CharField(choices=[('Naqd', 'Naqd'), ('Karta', 'Karta'), ("O'tkazma", "O'tkazma")], default='Naqd', max_length=10, verbose_name="To'lov usuli")),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Qabul qilgan xodim')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='installments.installmentplan', verbose_name='Nasiya Rejasi')),
            ],
            options={
                'verbose_name': "Nasiya To'lovi",
                'verbose_name_plural': "Nasiya To'lovlari",
                'ordering': ['-payment_date'],
            },
        ),
    ]
