# Generated by Django 5.2 on 2025-05-01 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0001_initial'),
        ('users', '0002_userprofile_address_userprofile_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='users.store', verbose_name="Do'kon"),
            preserve_default=False,
        ),
    ]
