# Generated by Django 5.2 on 2025-05-04 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installments', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_plans', to='sales.customer', verbose_name='Mijoz'),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installmentplan', to='sales.sale', verbose_name='Asosiy Sotuv'),
        ),
        migrations.AddField(
            model_name='installmentpayment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='installments.installmentplan', verbose_name='Nasiya Rejasi'),
        ),
    ]
