# Generated by Django 5.2 on 2025-05-06 04:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentplan',
            name='next_payment_date',
        ),
        migrations.RemoveField(
            model_name='installmentplan',
            name='total_due',
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name="Boshlang'ich To'lov (UZS)"),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='initial_amount',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Nasiya olingandagi asl narx (foizsiz)', max_digits=17, verbose_name='Mahsulot Narxi (UZS)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Nasiya uchun qo'shiladigan umumiy foiz (butun muddat uchun)", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Foiz Stavka (%)'),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name="Taxminiy Oylik To'lov (UZS)"),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='term_months',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Muddat (oylar)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='total_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=17, verbose_name="Jami To'lanishi Kerak (Foiz Bilan, UZS)"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Boshlang'ich to'lovni ham o'z ichiga oladi", max_digits=17, verbose_name="Jami To'langan (UZS)"),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='return_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Qaytarish Tuzatishi (UZS)'),
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name="To'lov Sanasi")),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=17, verbose_name="To'lanishi Kerak Summa")),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name="Haqiqatda To'langan")),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langan")),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name="Haqiqiy To'lov Sanasi")),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='installments.installmentplan', verbose_name='Nasiya Rejasi')),
            ],
            options={
                'verbose_name': "To'lov Grafigi Yozuvi",
                'verbose_name_plural': "To'lov Grafigi Yozuvlari",
                'ordering': ['plan', 'due_date'],
                'unique_together': {('plan', 'due_date')},
            },
        ),
    ]
