# Generated by Django 5.2 on 2025-05-10 12:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0003_alter_installmentplan_total_amount_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentplan',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=17, verbose_name="Jami To'langan (UZS)"),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='initial_amount',
            field=models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Mahsulot Narxi (UZS)'),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Foiz Stavka (%)'),
        ),
    ]
