# Generated by Django 5.2 on 2025-05-12 03:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0004_alter_installmentplan_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='currency',
            field=models.CharField(choices=[('UZS', "O'zbek so'mi"), ('USD', 'AQSH dollari')], default=1, max_length=3, verbose_name='Nasiya Valyutasi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=17, verbose_name="Jami To'langan (nasiya valyutasida)"),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=17, verbose_name="Boshlang'ich To'lov (nasiya valyutasida)"),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='initial_amount',
            field=models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Asosiy Qarz Summasi (nasiya valyutasida)'),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Foiz Stavka (%)'),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name="Taxminiy Oylik To'lov (nasiya valyutasida)"),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='return_adjustment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=17, verbose_name='Qaytarish Tuzatishi (nasiya valyutasida)'),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='total_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name="Jami To'lanishi Kerak (nasiya valyutasida)"),
        ),
    ]
