# Generated by Django 5.2 on 2025-05-09 05:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdor (+/-)')),
                ('operation_type', models.CharField(choices=[('ADD', "Qo'shish (Kirim)"), ('REMOVE', 'Chiqarish (Hisobdan chiqarish)'), ('TRANSFER_OUT', "Ko'chirish (Chiqish)"), ('TRANSFER_IN', "Ko'chirish (Kirish)"), ('SALE', 'Sotuv'), ('RETURN', 'Qaytarish'), ('INITIAL', "Boshlang'ich qoldiq")], max_length=20, verbose_name='Amaliyot turi')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana va vaqt')),
                ('kassa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_operations', to='products.kassa', verbose_name='Kassa/Filial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_operations', to='products.product', verbose_name='Mahsulot')),
                ('related_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_pair', to='inventory.inventoryoperation', verbose_name="Bog'liq amaliyot (Ko'chirish)")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_operations', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi (Amaliyotchi)')),
            ],
            options={
                'verbose_name': 'Ombor Amaliyoti',
                'verbose_name_plural': 'Ombor Amaliyotlari',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Miqdori (qoldiq)')),
                ('minimum_stock_level', models.PositiveIntegerField(default=5, verbose_name='Minimal miqdor')),
                ('kassa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.kassa', verbose_name='Kassa/Filial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': "Ombor Qoldig'i",
                'verbose_name_plural': 'Ombor Qoldiqlari',
                'ordering': ['kassa', 'product__name'],
                'unique_together': {('product', 'kassa')},
            },
        ),
    ]
