# Generated by Django 5.2 on 2025-05-14 06:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0004_alter_product_price_uzs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Yetkazib beruvchi nomi/ismi')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzili')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name="Bog'lanish uchun shaxs")),
            ],
            options={
                'verbose_name': 'Yetkazib Beruvchi',
                'verbose_name_plural': 'Yetkazib Beruvchilar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Xarid Sanasi')),
                ('currency_choices', models.CharField(choices=[('UZS', "O'zbek so'mi"), ('USD', 'AQSH dollari')], default='UZS', max_length=3, verbose_name='Xarid Valyutasi')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=17, verbose_name='Umumiy Xarid Summasi (xarid valyutasida)')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=17, verbose_name="To'langan Summa (xarid valyutasida)")),
                ('status', models.CharField(choices=[('Pending', 'Kutilmoqda'), ('Partially Received', 'Qisman Qabul Qilindi'), ('Received', "To'liq Qabul Qilindi"), ('Cancelled', 'Bekor Qilingan')], default='Pending', max_length=20, verbose_name='Xarid Holati')),
                ('payment_status', models.CharField(choices=[('Unpaid', "To'lanmagan"), ('Partially Paid', "Qisman To'langan"), ('Paid', "To'liq To'langan")], default='Unpaid', max_length=20, verbose_name="To'lov Holati")),
                ('due_date_for_remaining', models.DateField(blank=True, null=True, verbose_name="Qolgan To'lov Sanasi")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan Xodim')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='inventory.supplier', verbose_name='Yetkazib Beruvchi')),
            ],
            options={
                'verbose_name': 'Xarid Operatsiyasi',
                'verbose_name_plural': 'Xarid Operatsiyalari',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Buyurtma Qilingan Miqdor')),
                ('quantity_received', models.PositiveIntegerField(default=0, verbose_name='Qabul Qilingan Miqdor')),
                ('purchase_price_currency', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Xarid Narxi (bir dona uchun, xarid valyutasida)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='products.product', verbose_name='Mahsulot')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder', verbose_name='Xarid Operatsiyasi')),
                ('target_kassa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_purchase_items', to='products.kassa', verbose_name='Maqsadli Kassa/Ombor')),
            ],
            options={
                'verbose_name': 'Xarid Elementi',
                'verbose_name_plural': 'Xarid Elementlari',
                'unique_together': {('purchase_order', 'product', 'target_kassa')},
            },
        ),
    ]
