# Generated by Django 5.2 on 2025-05-03 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tarif Nomi')),
                ('price_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Narxi (UZS)')),
                ('product_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mahsulot Limiti')),
                ('branch_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Filial (Kassa) Limiti')),
                ('user_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Xodim Limiti')),
                ('allow_installments', models.BooleanField(default=False, verbose_name='Nasiya Savdoga Ruxsat')),
                ('allow_multi_currency', models.BooleanField(default=False, verbose_name="Ko'p Valyutali Tizim")),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv Tarif')),
            ],
            options={
                'verbose_name': 'Obuna Tarifi',
                'verbose_name_plural': 'Obuna Tariflari',
                'ordering': ['price_uzs'],
            },
        ),
    ]
