# Generated by Django 5.2 on 2025-05-09 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_uzs_rate', models.DecimalField(decimal_places=2, default=13000.0, max_digits=15, verbose_name='USD->UZS Kursi')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name="So'nggi yangilanish")),
            ],
            options={
                'verbose_name': 'Valyuta Kursi',
                'verbose_name_plural': 'Valyuta Kurslari',
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default="Smart POS Do'koni", max_length=255, verbose_name="Do'kon nomi")),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': "Do'kon Sozlamasi",
                'verbose_name_plural': "Do'kon Sozlamalari",
            },
        ),
    ]
