# Generated by Django 5.2 on 2025-05-12 03:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='amount_paid_uzs',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_amount_usd',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_amount_uzs',
        ),
        migrations.AddField(
            model_name='sale',
            name='amount_paid_currency',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=17, verbose_name="To'langan Summa (sotuv valyutasida)"),
        ),
        migrations.AddField(
            model_name='sale',
            name='currency',
            field=models.CharField(choices=[('UZS', "O'zbek so'mi"), ('USD', 'AQSH dollari')], default='UZS', max_length=3, verbose_name='Sotuv Valyutasi'),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_amount_currency',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=17, verbose_name='Umumiy Summa (sotuv valyutasida)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('Naqd', 'Naqd'), ('Karta', 'Karta'), ('Nasiya', 'Nasiya')], max_length=10, verbose_name="To'lov turi"),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price_at_sale_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Narx (USD) (sotuv paytida)'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price_at_sale_uzs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Narx (UZS) (sotuv paytida)'),
        ),
    ]
