# Generated by Django 5.2 on 2025-04-30 12:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Qaytarish sababi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Qaytarilgan sana')),
                ('total_returned_amount_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Jami qaytarilgan summa (UZS)')),
                ('original_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.sale', verbose_name='Asl Sotuv')),
                ('returned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Qaytaruvchi Xodim')),
            ],
            options={
                'verbose_name': 'Sotuv Qaytarish',
                'verbose_name_plural': 'Sotuv Qaytarishlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.PositiveIntegerField(verbose_name='Qaytarilgan miqdor (shu operatsiyada)')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.saleitem', verbose_name='Asl Sotuv Elementi')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salereturn', verbose_name='Qaytarish Operatsiyasi')),
            ],
            options={
                'verbose_name': 'Qaytarilgan Element',
                'verbose_name_plural': 'Qaytarilgan Elementlar',
            },
        ),
    ]
