# Generated by Django 5.2 on 2025-05-01 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salereturn_salereturnitem'),
        ('users', '0002_userprofile_address_userprofile_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='users.store', verbose_name="Do'kon"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='users.store', verbose_name="Do'kon"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('store', 'phone_number')},
        ),
    ]
