# Generated by Django 5.2 on 2025-05-01 21:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0002_installmentplan_store'),
        ('products', '0003_alter_product_price_usd_alter_product_price_uzs_and_more'),
        ('sales', '0003_customer_store_sale_store_and_more'),
        ('users', '0002_userprofile_address_userprofile_salary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KassaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Summa (UZS)')),
                ('transaction_type', models.CharField(choices=[('SALE', 'Sotuvdan Kirim'), ('INSTALLMENT', 'Nasiyadan Kirim'), ('CASH_IN', 'Kirim (Boshqa)'), ('CASH_OUT', 'Chiqim (Xarajat)'), ('REFUND', 'Qaytarish (Chiqim)')], max_length=20, verbose_name='Amaliyot Turi')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana va Vaqt')),
                ('kassa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='products.kassa', verbose_name='Kassa')),
                ('related_installment_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kassa_transactions', to='installments.installmentpayment')),
                ('related_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kassa_transactions', to='sales.salereturn')),
                ('related_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kassa_transactions', to='sales.sale')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kassa_transactions', to='users.store', verbose_name="Do'kon")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Kassa Amaliyoti',
                'verbose_name_plural': 'Kassa Amaliyotlari',
                'ordering': ['-timestamp'],
            },
        ),
    ]
