# Generated by Django 5.2 on 2025-05-26 08:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_sale_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salereturn',
            name='total_returned_amount_uzs',
        ),
        migrations.AddField(
            model_name='kassatransaction',
            name='currency',
            field=models.CharField(choices=[('UZS', "O'zbek so'mi"), ('USD', 'AQSH dollari')], default='UZS', max_length=3, verbose_name='Amaliyot Valyutasi'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='original_price_at_sale_usd_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Asl Narx (USD) (element uchun)'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='original_price_at_sale_uzs_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Asl Narx (UZS) (element uchun)'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='currency_of_return',
            field=models.CharField(choices=[('UZS', "O'zbek so'mi"), ('USD', 'AQSH dollari')], default='UZS', max_length=3, verbose_name='Qaytarish Valyutasi'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='returned_amount_currency_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=17, verbose_name='Jami qaytarilgan summa (qaytarish valyutasida)'),
        ),
        migrations.AlterField(
            model_name='kassatransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Summa (amaliyot valyutasida)'),
        ),
        migrations.AlterField(
            model_name='kassatransaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALE', 'Sotuvdan Kirim'), ('INSTALLMENT', 'Nasiyadan Kirim'), ('CASH_IN', 'Kirim (Boshqa)'), ('CASH_OUT', 'Chiqim (Xarajat)'), ('REFUND', 'Qaytarish (Chiqim)'), ('EXCHANGE_SELL', 'Valyuta Sotish (Chiqim)'), ('EXCHANGE_BUY', 'Valyuta Olish (Kirim)')], max_length=20, verbose_name='Amaliyot Turi'),
        ),
    ]
