# Generated by Django 5.2 on 2025-05-04 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsifi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Kassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Joylashuvi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Kassa/Filial',
                'verbose_name_plural': 'Kassalar/Filiallar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Shtrix-kod')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sotish Narxi (USD)')),
                ('price_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='Sotish Narxi (UZS)')),
                ('purchase_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Olingan Narxi (USD)')),
                ('purchase_price_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='Olingan Narxi (UZS)')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Olingan Sana')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsifi (ixtiyoriy)')),
                ('storage_capacity', models.CharField(blank=True, max_length=50, null=True, verbose_name="Sig'imi (Masalan: 128GB)")),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rangi')),
                ('series_region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seriyasi (Region, Masalan: LL/A)')),
                ('battery_health', models.PositiveIntegerField(blank=True, null=True, verbose_name='Batareya Holati (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['name'],
            },
        ),
    ]
