# Generated by Django 5.2 on 2025-05-09 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='barcode_prefix',
            field=models.CharField(blank=True, help_text="Ushbu kategoriyadagi mahsulotlar shtrix-kodi uchun boshlang'ich belgi(lar).", max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Faqat harf va raqamlar ruxsat etilgan.')], verbose_name='Shtrix-kod Prefiksi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price_uzs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Olingan Narxi (UZS)'),
        ),
    ]
