# Generated by Django 5.2 on 2025-05-01 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0002_userprofile_address_userprofile_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='users.store', verbose_name="Do'kon (Global uchun null)"),
        ),
        migrations.AddField(
            model_name='kassa',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kassas', to='users.store', verbose_name="Do'kon"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='battery_health',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Batareya Holati (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rangi'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Olingan Sana'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Olingan Narxi (USD)'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price_uzs',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=15, verbose_name='Olingan Narxi (UZS)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='series_region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Seriyasi (Region)'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_capacity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Sig'imi (Yomkost)"),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.store', verbose_name="Do'kon"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('store', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='kassa',
            unique_together={('store', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('store', 'barcode')},
        ),
    ]
