# Generated by Django 5.2 on 2025-05-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_barcode_prefix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sotish Narxi (USD)'),
        ),
    ]
