# Generated by Django 5.2 on 2025-05-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_store_kassa_store_product_battery_health_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sotish Narxi (USD)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_uzs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='Sotish Narxi (UZS)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='series_region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Seriyasi (Region, Masalan: LL/A)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage_capacity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Sig'imi (Masalan: 128GB)"),
        ),
    ]
