# Generated by Django 5.2 on 2025-05-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_price_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_uzs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Sotish Narxi (UZS)'),
        ),
    ]
