# Generated by Django 5.2 on 2025-05-15 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_barcode_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='barcode_prefix',
            field=models.CharField(blank=True, help_text="Bu kategoriya uchun shtrix-kod boshlanadigan belgi(lar). Masalan: 'IPH', '01', 'SAM'.", max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Faqat harf va raqamlar ruxsat etilgan.')], verbose_name='Shtrix-kod Prefiksi'),
        ),
    ]
