# Generated by Django 5.2 on 2025-05-17 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_barcode_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='barcode_prefix',
            field=models.CharField(blank=True, help_text="Bu kategoriya uchun Application Identifier (masalan, '01', '02'). Qavssiz kiriting.", max_length=5, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Faqat raqamlar ruxsat etilgan.')], verbose_name='Shtrix-kod Prefiksi (AI uchun raqamlar)'),
        ),
    ]
