# Generated by Django 5.2 on 2025-05-19 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_barcode_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='barcode_prefix',
            field=models.CharField(blank=True, help_text="Bu kategoriya uchun shtrix-kod boshlanadigan belgi(lar). Masalan: 'IPH', '01'.", max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Faqat harf va raqamlar ruxsat etilgan.')], verbose_name='Shtrix-kod Prefiksi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Shtrix-kod / IMEI'),
        ),
    ]
