# Generated by Django 5.2 on 2025-05-22 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_barcode_prefix_alter_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_kassa_for_new_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_new_products_stock', to='products.kassa', verbose_name="Yangi mahsulot uchun standart kassa (omborga qo'shish uchun)"),
        ),
    ]
