# Generated by Django 5.2 on 2025-05-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_default_kassa_for_new_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_accessory_category',
            field=models.BooleanField(default=False, verbose_name='Bu aksessuar kategoriyasimi?'),
        ),
    ]
