# Generated by Django 5.2 on 2025-05-31 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_is_accessory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_name_manual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Yetkazib Beruvchi Ismi (Qo'lda)"),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_phone_manual',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami to'g'ri formatda emas (masalan, +998901234567 yoki 901234567).", regex='^\\+?1?\\d{9,15}$')], verbose_name="Yetkazib Beruvchi Telefon Raqami (Qo'lda)"),
        ),
    ]
